language: ruby
cache: bundler
sudo: false
before_install: gem install bundler -v 1.11.2
rvm:
  - "2.3.1"
  - "2.3.0"
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.9.3"
  - ruby-head
  - rbx-2
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
