language: ruby
sudo: false
rvm:
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.9.3"
  - ruby-head
  - rbx-2
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
