language: ruby
cache: bundler
sudo: false
before_install: gem install bundler -v 1.14.6
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2
  - 2.1
  - 2.0
  - ruby-head
  - jruby-1.7.26
  - jruby-head
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--2.0"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
