language: ruby
cache: bundler
sudo: false
before_install:
  - gem update --system
  - gem install bundler -v 2.0.2
rvm:
  - 2.6
  - 2.5
  - 2.4
  - jruby-9.2.9.0
  - jruby-9.1.17
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
